<?php
session_start();
unset($_SESSION['clas']);
unset($_SESSION['text']);
unset($_SESSION['error_username']);
unset($_SESSION['error_email']);
unset($_SESSION['error_parol']);
unset($_SESSION['error_bio']);
unset($_SESSION['error_sub']);
unset($_SESSION['error_mes']);
unset($_SESSION['error_user']);
unset($_SESSION['success_mes']);
unset($_SESSION['username']);
unset($_SESSION['email']);
unset($_SESSION['pass']);
unset($_SESSION['bio']);
unset($_SESSION['sub']);
unset($_SESSION['des']);
?>
